<template>
    <div id="page-garbage">
        <header class="header-top row">
            <div class="left-icon start-center" @click="handleReturnHome"><van-icon color="white" size="20px" name="arrow-left"/></div>
            <div class="top-title center">垃圾分类</div>
            <div class="right-icon center"></div>
        </header>
        <div class="search center" @click="handleSearch">
            搜索垃圾查看对应分类
        </div>
        <div class="type row" v-if="show">
            <div class="per-type center" :class="active == '1' ? 'active' : ''" @click="handleChecked('1')">湿垃圾</div>
            <div class="per-type center" :class="active == '2' ? 'active' : ''" @click="handleChecked('2')">干垃圾</div>
            <div class="per-type center" :class="active == '3' ? 'active' : ''" @click="handleChecked('3')">可回收物</div>
            <div class="per-type center" :class="active == '4' ? 'active' : ''" @click="handleChecked('4')">有害垃圾</div>
        </div>
        <div class="detail" v-if="show">
            <!-- 湿垃圾 -->
            <div class="detail-one" v-if="active == '1'">
                <div class="top">
                    <div class="title-desc">
                        <span style="font-weight: 700">湿垃圾</span>是指易腐的生物质废弃垃圾，包括剩饭剩菜、瓜果皮核、花蕊绿植、肉类碎骨、过期食品、餐厨垃圾等。
                    </div>
                    <h1 style="font-weight: 700">投放要求:</h1>
                    <p>(1):纯流质的食物垃圾，如牛奶等，应直接倒进下水口。</p>
                    <p>(2):有包装物的湿垃圾应将包装物取出后分类投放，包装物请投放到对应的可回收物容器或干垃圾容器</p>
                </div>
                <div class="list">
                    <div v-for="(item,index) in options_shi" :key="index">{{item.name}}</div>
                </div>
            </div>
            <!-- 干垃圾 -->
            <div class="detail-one" v-if="active == '2'">
                <div class="top">
                    <div class="title-desc">
                        <span style="font-weight: 700">干垃圾</span>是指除有害垃圾、可回收物、湿垃圾以外的生活废弃物。
                    </div>
                    <h1 style="font-weight: 700">投放要求:</h1>
                    <p>(1):尽量沥干水分。</p>
                    <p>(2):难以辨别的生活垃圾投入干垃圾容器内</p>
                </div>
                <div class="list">
                    <div class="start-center" v-for="(item,index) in options_gan" :key="index">{{item.name}}</div>
                </div>
            </div>
            <!-- 可回收物 -->
            <div class="detail-one" v-if="active == '3'">
                <div class="top">
                    <div class="title-desc">
                        <span style="font-weight: 700">可回收物</span>是指适宜回收和可循环再利用的废弃物。主要包括废玻璃、废金属、废塑料、废纸张、废织物等。
                    </div>
                    <h1 style="font-weight: 700">投放要求:</h1>
                    <p>(1):轻投轻放。</p>
                    <p>(2):清洁干燥，避免污染</p>
                    <p>(3):废纸尽量平整</p>
                    <p>(4):立体包装请清空内容物，清洁后压扁投放</p>
                    <p>(5):有尖锐边角的，应包裹后投放</p>
                </div>
                <div class="list">
                    <div class="strat-center" v-for="(item,index) in options_hui" :key="index">{{item.name}}</div>
                </div>
            </div>
            <!-- 有害垃圾 -->
            <div class="detail-one" v-if="active == '4'">
                <div class="top">
                    <div class="title-desc">
                        <span style="font-weight: 700">有害垃圾</span>是指对人体健康或者自然环境造成直接或者潜在危害的零星废弃物，单位集中产生的除外。主要包括废电池、废灯管、废油漆桶等。
                    </div>
                    <h1 style="font-weight: 700">投放要求:</h1>
                    <p>(1):充电电池、纽扣电池、蓄电池投放时请注意轻放。</p>
                    <p>(2):油漆桶、杀虫剂如有残留请密闭后投放</p>
                    <p>(3):荧光灯、节能灯易破损请连带包装或包裹后轻放</p>
                    <p>(4):废药品极其包装连带包装一起投放</p>
                </div>
                <div class="list">
                    <div class="start-center" v-for="(item,index) in options_hai" :key="index">{{item.name}}</div>
                </div>
            </div>
        </div>
        <transition name="van-slide-right">
            <div class="answer" v-if="!show">
                <div class="top row">
                    <div>
                        <input type="text" class="input" v-model="value" placeholder="搜索垃圾查看对应分类" @blur="handleKeyWord"/>
                    </div>
                    <div class="cancel center" @click="handleCancel">取消</div>
                </div>
                <div class="list">
                    <div class="start-center" v-for="(item,index) in list" :key="index">{{item.name}}<span style="font-weight: 700;color:red">[{{item.type}}]</span></div>
                </div>
            </div>
        </transition>
    </div>
</template>
<script>
import garbage from '@/lib/garbage'
export default {
    data(){
        return{
            active: '1',
            value: '',
            show: true,
            list: [],
            options_hai: [
                {"name":"充电电池"},
                {"name":"镍镉电池"},
                {"name":"纽扣电池"},
                {"name":"药片盒"},
                {"name":"玻璃小药瓶"},
                {"name":"没有药的空药瓶"},
                {"name":"老鼠药"},
                {"name":"口服液瓶子"},
                {"name":"废油漆桶"},
                {"name":"药品铝塑板"},
                {"name":"口服液瓶"},
                {"name":"指甲油"},
                {"name":"胶囊"},
                {"name":"白炽灯泡"},
                {"name":"有害垃圾"},
                {"name":"药品"},
                {"name":"药瓶"},
                {"name":"塑料药瓶"},
                {"name":"过期胶囊药物"},
                {"name":"乳胶漆"},
                {"name":"过期指甲油"},
                {"name":"喝完的药瓶"},
                {"name":"灯泡"},
                {"name":"药丸"},
                {"name":"过期药"},
                {"name":"油漆"},
                {"name":"农药瓶"},
                {"name":"蟑螂药"},
                {"name":"各类过期药品"},
                {"name":"喷蟑螂瓶"},
                {"name":"中成药"},
                {"name":"废含汞血压计"},
                {"name":"杀虫喷雾罐"},
                {"name":"废直式日光灯管"},
                {"name":"漂白剂罐"},
                {"name":"咳嗽糖浆"},
                {"name":"废弃药品"},
                {"name":"卤素灯"},
                {"name":"吸顶灯"},
                {"name":"维生素"},
                {"name":"电灯泡"},
                {"name":"杀虫剂"},
                {"name":"药片"},
                {"name":"X光片"},
                {"name":"LED灯"},
                {"name":"指甲油瓶"},
                {"name":"废弃荧光灯"},
                {"name":"x光片"},
                {"name":"x光胶片"},
                {"name":"盐酸伐昔洛韦片"},
                {"name":"保健品"},
                {"name":"含汞体温计"},
                {"name":"废含汞温度计"},
                {"name":"除草剂"},
                {"name":"除草剂罐"}
            ],
            options_hui: [
                {"name":"牛奶盒"},
                {"name":"塑料酸奶盒"},
                {"name":"矿泉水瓶"},
                {"name":"纸"},
                {"name":"珍珠"},
                {"name":"玻璃"},
                {"name":"手机"},
                {"name":"塑料"},
                {"name":"痰盂罐"},
                {"name":"酸奶盒"},
                {"name":"塑料盒"},
                {"name":"塑料酸奶瓶"},
                {"name":"化妆品空瓶"},
                {"name":"塑料瓶"},
                {"name":"拖鞋"},
                {"name":"衣服"},
                {"name":"充电宝"},
                {"name":"玻璃瓶"},
                {"name":"塑料瓶"},
                {"name":"旧鞋子"},
                {"name":"易拉罐"},
                {"name":"牛奶盒"},
                {"name":"牛奶纸盒"},
                {"name":"化妆品罐"},
                {"name":"泡沫板"},
                {"name":"纸盒"},
                {"name":"铝喷雾瓶"},
                {"name":"塑料勺子"},
                {"name":"香烟盒"},
                {"name":"碎玻璃"},
                {"name":"袜子"},
                {"name":"废纸"},
                {"name":"饮料盒"},
                {"name":"饮料瓶"},
                {"name":"可乐瓶"},
                {"name":"塑料杯"},
                {"name":"玻璃杯"},
                {"name":"香水瓶"},
                {"name":"化妆水瓶"},
                {"name":"纸袋"},
                {"name":"电脑"},
                {"name":"黄金"},
                {"name":"洗发水瓶"},
                {"name":"卷筒卫生纸纸芯"},
                {"name":"塑料饭盒"},
                {"name":"木筷子"},
                {"name":"旧运动鞋"},
                {"name":"报纸"},
                {"name":"打印机墨盒"},
                {"name":"鞋子"},
                {"name":"毛绒玩具"},
                {"name":"快递信封"},
                {"name":"包装纸"},
                {"name":"塑料盖子"},
                {"name":"花露水瓶"},
                {"name":"牛奶利乐盒"},
                {"name":"A4纸"},
                {"name":"电动牙刷"},
                {"name":"保温杯"},
                {"name":"书"},
                {"name":"塑料咖啡杯"},
                {"name":"沐浴露瓶"},
                {"name":"充气娃娃"},
                {"name":"铁罐"},
                {"name":"数据线"},
                {"name":"快递盒"},
                {"name":"可降解塑料"},
                {"name":"包装纸盒"},
                {"name":"吊牌"},
                {"name":"笔记本电脑"},
                {"name":"防晒霜罐"},
                {"name":"护肤品空瓶"},
                {"name":"润肤露瓶子"},
                {"name":"收银小票"},
                {"name":"充电器"},
                {"name":"打印纸"},
                {"name":"乐扣乐扣塑料盒"},
                {"name":"泡沫塑料"},
                {"name":"剃须刀片"},
                {"name":"布"},
                {"name":"铁"},
                {"name":"合金玩具"},
                {"name":"玻璃调味瓶"},
                {"name":"饼干纸盒"},
                {"name":"草稿纸"},
                {"name":"除湿盒"},
                {"name":"pe塑料盒"},
                {"name":"订书机"},
                {"name":"精华液瓶"},
                {"name":"金属包装盒"},
                {"name":"罐头盒"},
                {"name":"美工刀"},
                {"name":"沐浴露塑料瓶"},
                {"name":"勺子"},
                {"name":"鼠标"},
                {"name":"电影票"},
                {"name":"旧枕头"},
                {"name":"利乐包装"},
                {"name":"耳机"},
                {"name":"剪刀"},
                {"name":"旧书"},
                {"name":"积木"},
                {"name":"牛皮纸"},
                {"name":"啤酒瓶"},
                {"name":"破袜子"},
                {"name":"垃圾桶"},
                {"name":"废纸盒"},
                {"name":"骑车空气滤清器"},
                {"name":"罐头食品"},
                {"name":"铁盒"},
                {"name":"洗衣液瓶"},
                {"name":"锅"},
                {"name":"油瓶"},
                {"name":"长毛绒玩具"},
                {"name":"电子垃圾"},
                {"name":"风油精瓶"},
                {"name":"酱油瓶"},
                {"name":"毛衣"},
                {"name":"木梳子"},
                {"name":"啤酒盖"},
                {"name":"电风扇"},
                {"name":"非手机"},
                {"name":"电子塑料包装"},
                {"name":"信用卡"},
                {"name":"电脑机箱"},
                {"name":"电线"},
                {"name":"耳机线"},
                {"name":"钢化玻璃"},
                {"name":"乳液罐"},
                {"name":"电热水瓶"},
                {"name":"键盘"},
                {"name":"靠垫"},
                {"name":"螺丝"},
                {"name":"手表"},
                {"name":"塑料管"},
                {"name":"洗洁精瓶"},
                {"name":"遥控器"},
                {"name":"自慰器"},
                {"name":"利乐砖"},
                {"name":"手套"},
                {"name":"压力罐"},
                {"name":"啤酒罐"},
                {"name":"旧衣服"},
                {"name":"书包"},
                {"name":"书本"},
                {"name":"塑料碗"},
                {"name":"包包"},
                {"name":"报纸"},
                {"name":"食用油桶"},
                {"name":"果酱瓶"},
                {"name":"废铜烂铁"},
                {"name":"Ipad"},
                {"name":"铁棍"},
                {"name":"冰箱"},
                {"name":"不锈钢杯子"},
                {"name":"木质菜板"},
                {"name":"醋瓶"},
                {"name":"皮手套"},
                {"name":"床上用品"},
                {"name":"除湿机"},
                {"name":"充电式暖宝宝"},
                {"name":"广告单"},
                {"name":"干净的塑料"},
                {"name":"红酒瓶"},
                {"name":"坏电视机"},
                {"name":"胡须刀"},
                {"name":"金属"},
                {"name":"废金属"},
                {"name":"驱蚊瓶"},
                {"name":"电扇"},
                {"name":"风扇"},
                {"name":"充气沙发"},
                {"name":"相册"},
                {"name":"废旧洗衣机"},
                {"name":"U盘"},
                {"name":"枕头"},
                {"name":"充电热水袋"},
                {"name":"笔记本"},
                {"name":"布料"},
                {"name":"放大镜"},
                {"name":"玻璃制容器"},
                {"name":"金属制容器"},
                {"name":"窗帘"},
                {"name":"杯子"},
                {"name":"玻璃器皿"},
                {"name":"吹风机"},
                {"name":"接线板"},
                {"name":"拖线板"},
                {"name":"茶叶罐"},
                {"name":"电吹风"},
                {"name":"玩具"},
                {"name":"电蚊拍"},
                {"name":"吸铁石"},
                {"name":"锁"},
                {"name":"钥匙"},
                {"name":"不粘锅"},
                {"name":"海报"},
                {"name":"废酒瓶"},
                {"name":"废家电"},
                {"name":"计算器"},
                {"name":"玩偶"},
                {"name":"Kt板"},
                {"name":"裤子"},
                {"name":"卡纸"},
                {"name":"乐高"},
                {"name":"螺丝刀路由器"},
                {"name":"铝制品"},
                {"name":"棉被"},
                {"name":"美工刀片"},
                {"name":"名片"},
                {"name":"面霜罐子"},
                {"name":"墨水瓶"},
                {"name":"毛毯"},
                {"name":"手办"},
                {"name":"说明书"},
                {"name":"摄像头"},
                {"name":"机油桶"},
                {"name":"银手镯"},
                {"name":"网线"},
                {"name":"信封"},
                {"name":"芯片"},
                {"name":"亚克力"},
                {"name":"羊毛"},
                {"name":"游戏机"},
                {"name":"砧板"},
                {"name":"钻石"},
                {"name":"叉子"},
                {"name":"音箱"},
                {"name":"移动电源"},
                {"name":"花洒"},
                {"name":"显卡"},
                {"name":"试卷"},
                {"name":"易拉宝"},
                {"name":"水果刀"},
                {"name":"日历"},
                {"name":"话筒"},
                {"name":"玻璃灯罩"},
                {"name":"塑料制品"},
                {"name":"电饭锅"},
                {"name":"帐篷"},
                {"name":"铁板"},
                {"name":"相片"},
                {"name":"秋衣"},
                {"name":"玉镯"},
                {"name":"计算机"},
                {"name":"旧棉絮"},
                {"name":"连裤袜"},
                {"name":"灭火器"},
                {"name":"电钻"},
                {"name":"木碗"},
                {"name":"排插"},
                {"name":"布面粉袋"},
                {"name":"公仔"},
                {"name":"牛仔裤"},
                {"name":"呼叫器"},
                {"name":"高附加值可回收物"},
                {"name":"电脑小音响"},
                {"name":"公交卡"},
                {"name":"安全帽"},
                {"name":"被芯"},
                {"name":"被套"},
                {"name":"被单"},
                {"name":"纱手套"},
                {"name":"电话"},
                {"name":"防潮盒"},
                {"name":"高跟鞋"},
                {"name":"瘪掉的篮球"},
                {"name":"钢丝"},
                {"name":"工资卡"},
                {"name":"空气净化器"},
                {"name":"清洁瓶"},
                {"name":"空调"},
                {"name":"明信片"}
            ],
            options_shi: [
                {"name":"鸡蛋壳"},
                {"name":"玉米棒"},
                {"name":"蛋壳"},
                {"name":"熟鸡蛋壳"},
                {"name":"玉米"},
                {"name":"小龙虾"},
                {"name":"小龙虾壳"},
                {"name":"鸡骨头"},
                {"name":"桃核"},
                {"name":"香蕉皮"},
                {"name":"小龙虾头"},
                {"name":"蟑螂"},
                {"name":"熟玉米棒"},
                {"name":"龙虾"},
                {"name":"咖啡渣"},
                {"name":"人造奶油"},
                {"name":"西瓜皮"},
                {"name":"瓜子壳"},
                {"name":"毛豆壳"},
                {"name":"鸡蛋"},
                {"name":"龙虾壳"},
                {"name":"鱼刺"},
                {"name":"蟹壳"},
                {"name":"瓜子皮"},
                {"name":"白煮蛋壳"},
                {"name":"茶叶"},
                {"name":"西瓜籽"},
                {"name":"桃子"},
                {"name":"樱桃核"},
                {"name":"树叶"},
                {"name":"玉米心"},
                {"name":"废弃树叶"},
                {"name":"咖啡"},
                {"name":"剩菜"},
                {"name":"中药药渣"},
                {"name":"螃蟹壳"},
                {"name":"花生壳"},
                {"name":"玉米芯"},
                {"name":"大蒜"},
                {"name":"鲜花"},
                {"name":"火锅"},
                {"name":"蔬菜水果皮"},
                {"name":"米饭"},
                {"name":"厨房剩菜"},
                {"name":"咸鸭蛋壳"},
                {"name":"猪"},
                {"name":"死蟑螂"},
                {"name":"茶叶蛋"},
                {"name":"小核桃仁"},
                {"name":"仙人球"},
                {"name":"西瓜子"},
                {"name":"鱼骨头"},
                {"name":"粥"},
                {"name":"螃蟹壳"},
                {"name":"葱油饼"},
                {"name":"瓜子花生壳"},
                {"name":"大闸蟹壳"},
                {"name":"干瓜子壳"},
                {"name":"黄瓜"},
                {"name":"火龙果皮"},
                {"name":"话梅"},
                {"name":"死老鼠"},
                {"name":"荔枝核"},
                {"name":"珍珠米"},
                {"name":"奶粉"},
                {"name":"苹果壳"},
                {"name":"带鱼骨头"},
                {"name":"樱桃"},
                {"name":"枣子核"},
                {"name":"火腿肠"},
                {"name":"呕吐物"},
                {"name":"玉米穗"},
                {"name":"兔头"},
                {"name":"鱼骨"},
                {"name":"蒜皮"},
                {"name":"虾头"},
                {"name":"棒棒糖"},
                {"name":"蚕豆壳"},
                {"name":"面条"},
                {"name":"猫饲料"},
                {"name":"苍蝇"},
                {"name":"鱼"},
                {"name":"碎骨头"},
                {"name":"吃菜剩下的鱼骨头"},
                {"name":"蛋黄"},
                {"name":"枯萎的鲜花"},
                {"name":"方便面"},
                {"name":"番茄酱"},
                {"name":"果冻"},
                {"name":"狗粮"},
                {"name":"贝壳肉"},
                {"name":"杏仁"},
                {"name":"臭鸡蛋"},
                {"name":"食物残渣"},
                {"name":"枯树叶"},
                {"name":"荔枝壳"},
                {"name":"榴莲干"},
                {"name":"馒头"},
                {"name":"牛排骨"},
                {"name":"苹果果核"},
                {"name":"葡萄"},
                {"name":"吃剩下的葡萄杆"},
                {"name":"剩菜剩饭"},
                {"name":"香瓜子"},
                {"name":"香瓜子壳"},
                {"name":"香蕉"},
                {"name":"粽子"},
                {"name":"槟榔"},
                {"name":"鸡翅膀的骨头"},
                {"name":"过期面包"},
                {"name":"厨余"},
                {"name":"喝过的茶叶"},
                {"name":"冰淇淋"},
                {"name":"中药残渣"},
                {"name":"苹果核"},
                {"name":"葡萄皮"},
                {"name":"金鱼"},
                {"name":"南瓜子壳"},
                {"name":"枣核"},
                {"name":"鸭骨头"},
                {"name":"玉米杆"},
                {"name":"泡过的茶叶"},
                {"name":"小排骨"},
                {"name":"草"},
                {"name":""},
                {"name":"茶"},
                {"name":"草"},
                {"name":"米"},
                {"name":"糖"},
                {"name":"蛋"},
                {"name":"爆米花"},
                {"name":"冬枣核"},
                {"name":"干花生壳"},
                {"name":"橙子皮"},
                {"name":"菜"},
                {"name":"残枝落叶"},
                {"name":"碎骨头"},
                {"name":"大葱"},
                {"name":"葵花籽"},
                {"name":"大猪蹄子"},
                {"name":"废弃植物"},
                {"name":"大闸蟹"},
                {"name":"蟹"},
                {"name":"大螃蟹壳"},
                {"name":"瓜果"},
                {"name":"辣椒"},
                {"name":"泡过的枸杞子"},
                {"name":"废树叶"},
                {"name":"废弃的树叶"},
                {"name":"吃过的甘蔗"},
                {"name":"火锅底料"},
                {"name":"花椒"},
                {"name":"干花生皮"},
                {"name":"红薯"},
                {"name":"叶"},
                {"name":"红枣"},
                {"name":"鸡"},
                {"name":"酒酿"},
                {"name":"鸡腿"},
                {"name":"橘子皮"},
                {"name":"残渣剩饭"},
                {"name":"豆渣"},
                {"name":"枯萎的花"},
                {"name":"荔枝干"},
                {"name":"薯片"},
                {"name":"大龙虾"},
                {"name":"荔枝干壳"},
                {"name":"面包屑"},
                {"name":"毛豆"},
                {"name":"毛豆结"},
                {"name":"过期面粉"},
                {"name":"芒果干"},
                {"name":"芒果核"},
                {"name":"过期猫粮"},
                {"name":"麻辣烫"},
                {"name":"过期奶粉"},
                {"name":"牛肉"},
                {"name":"皮蛋壳"},
                {"name":"烂苹果"},
                {"name":"葡萄柄"},
                {"name":"馄饨"},
                {"name":"水草"},
                {"name":"土豆皮"},
                {"name":"桃子皮"},
                {"name":"包菜"},
                {"name":"叶子"},
                {"name":"香蕉干"},
                {"name":"鸭脖子"},
                {"name":"洋葱皮"},
                {"name":"鸡鸭骨头"},
                {"name":"腰果"},
                {"name":"过期的燕麦片"},
                {"name":"鱼肉"},
                {"name":"鱼鳞"},
                {"name":"抽油烟机油渣"},
                {"name":"鸡爪"},
                {"name":"猪爪"},
                {"name":"骨头"},
                {"name":"生猪肉"},
                {"name":"药渣"},
                {"name":"鸡翅"},
                {"name":"骨头 "},
                {"name":"厨房垃圾 "},
                {"name":"过期零食"},
                {"name":"田螺"},
                {"name":"没有泡过的茶叶"},
                {"name":"月饼"},
                {"name":"大猪蹄子"},
                {"name":"玫瑰花"},
                {"name":"甜瓜"},
                {"name":"瓜子仁"},
                {"name":"鸽子骨头"},
                {"name":"芹菜"},
                {"name":"黄芪"},
                {"name":"鸭屁股"},
                {"name":"香蕉"},
                {"name":"树皮"},
                {"name":"小骨"},
                {"name":"河豚"},
                {"name":"鱼头"},
                {"name":"猪肉"},
                {"name":"芒果皮"},
                {"name":"泡面调料"},
                {"name":"桂圆核"},
                {"name":"红糖"},
                {"name":"马肉"},
                {"name":"牛肉干"},
                {"name":"鱼骨头"},
                {"name":"猪骨头"},
                {"name":"鸡骨"},
                {"name":"苹果皮"},
                {"name":"水果皮"},
                {"name":"蒜皮"},
                {"name":"葡萄枝"},
                {"name":"剩饭剩菜"},
                {"name":"干茶叶"},
                {"name":"艾草"},
                {"name":"豆腐"},
                {"name":"臭豆腐"},
                {"name":"八角"},
                {"name":"菠萝干"},
                {"name":"菠萝蜜"},
                {"name":"面包"},
                {"name":"板栗壳"},
                {"name":"炒板栗"},
                {"name":"槟榔皮"},
                {"name":"爆米花"},
                {"name":"长生果壳"},
                {"name":"剩包子"},
                {"name":"葱"},
                {"name":"葱蒜"},
                {"name":"炒面"},
                {"name":"炒花生壳"},
                {"name":"花生米"},
                {"name":"车厘子"},
                {"name":"陈皮"},
                {"name":"三合一咖啡"},
                {"name":"面"},
                {"name":"茶叶"},
                {"name":"虫子"},
                {"name":"芭蕉叶"},
                {"name":"菜皮"},
                {"name":"青菜皮"},
                {"name":"橙子"},
                {"name":"宠物饲料"},
                {"name":"食物残渣"},
                {"name":"宠物饲料"},
                {"name":"饼干渣"},
                {"name":"大白菜"},
                {"name":"白菜"},
                {"name":"冬瓜"},
                {"name":"蔔萄籽"},
                {"name":"葵花籽壳"},
                {"name":"多肉植物"},
                {"name":"废弃植物"},
                {"name":"冬笋壳"},
                {"name":"动物内脏"},
                {"name":"蛋挞"},
                {"name":"内脏动物"},
                {"name":"废弃内脏"},
                {"name":"绿豆芽"},
                {"name":"吃过的方便面"},
                {"name":"梨"},
                {"name":"番茄皮"},
                {"name":"调味品"},
                {"name":"瓜果壳"},
                {"name":"干辣椒"},
                {"name":"辣条"},
                {"name":"瓜果皮"},
                {"name":"厨余果皮"},
                {"name":"瓜果皮"},
                {"name":"各类过期食品"},
                {"name":"巧克力"},
                {"name":"变质食品"},
                {"name":"风干食品"},
                {"name":"风干、晾晒的食品"},
                {"name":"阿尔卑斯糖"},
                {"name":"调味料"},
                {"name":"桂圆"},
                {"name":"干桂圆壳"},
                {"name":"桂圈干"},
                {"name":""},
                {"name":"甘蔗渣"},
                {"name":"花瓣"},
                {"name":"汉堡包"},
                {"name":"红肠"},
                {"name":"黄豆"},
                {"name":"黄瓜皮"},
                {"name":"菜花"},
                {"name":"花卉"},
                {"name":"绿植"},
                {"name":"胡椒粉"},
                {"name":"胡萝卜"},
                {"name":"萝干"},
                {"name":"红枣"},
                {"name":"辣椒酱"},
                {"name":"哈密瓜皮"},
                {"name":"蛏子肉"},
                {"name":"贝壳的肉"},
                {"name":"红薯皮"},
                {"name":"海苔"},
                {"name":"杏仁壳"},
                {"name":"黄油"},
                {"name":"菱白皮"},
                {"name":"韭菜"},
                {"name":"鸡翅膀"},
                {"name":"鸡棒骨"},
                {"name":"菌菇"},
                {"name":"桔梗"},
                {"name":"酱料"},
                {"name":"鸡皮"},
                {"name":"鸡肉"},
                {"name":"鸡腿骨"},
                {"name":"甲鱼"},
                {"name":"橘子"},
                {"name":"干橘子皮"},
                {"name":"桔子"},
                {"name":"桔子皮"},
                {"name":"炸鸡"},
                {"name":"炸鸡腿"},
                {"name":"淀粉"},
                {"name":"枯树枝"},
                {"name":"萝卜的叶子"},
                {"name":"绿豆"},
                {"name":"家庭绿化"},
                {"name":"家养绿植"},
                {"name":"绿萝"},
                {"name":"螺螺粉"},
                {"name":"螺蛎壳"},
                {"name":"腐烂蔬菜"},
                {"name":"烂水果"},
                {"name":"蔬菜水果"},
                {"name":"乐事薯片"},
                {"name":"马铃薯片"},
                {"name":"辣酱"},
                {"name":"栗子壳"},
                {"name":"炒栗子"},
                {"name":"蘑菇"},
                {"name":"猕猴桃"},
                {"name":"过期猫粮"},
                {"name":"南瓜皮"},
                {"name":"奶酪"},
                {"name":"柠檬"},
                {"name":"过期牛肉干"},
                {"name":"牛蛙"},
                {"name":"牛蛙骨头"},
                {"name":"碎骨"},
                {"name":"奶油"},
                {"name":"奶油蛋糕"},
                {"name":"牛油果"},
                {"name":"菠萝派"},
                {"name":"膨化食品"},
                {"name":"食品"},
                {"name":"枇杷叶"},
                {"name":"披萨"},
                {"name":"青菜"},
                {"name":"青菜杆"},
                {"name":"蕃茄酱"},
                {"name":"曲奇"},
                {"name":"青蟹壳"},
                {"name":"长生果"},
                {"name":"茄子"},
                {"name":"软糖"},
                {"name":"速冻饺子"},
                {"name":"水饺"},
                {"name":"笋壳"},
                {"name":"丝瓜瓤"},
                {"name":"扇贝"},
                {"name":"石榴皮"},
                {"name":"熟鸡蛋"},
                {"name":"沙拉酱"},
                {"name":"薯条"},
                {"name":"山楂片"},
                {"name":"发霉食物"},
                {"name":"过期食物"},
                {"name":"变质的食物"},
                {"name":"三文鱼"},
                {"name":"三文鱼皮"},
                {"name":"三文鱼片"},
                {"name":"山竹"},
                {"name":"山竹皮"},
                {"name":"梭子蟹"},
                {"name":"午餐肉"},
                {"name":"豌豆壳"},
                {"name":"豌豆"},
                {"name":"过期糕点"},
                {"name":"香榧子"},
                {"name":"香榧子外壳"},
                {"name":"猪蹄子"},
                {"name":"西红柿"},
                {"name":"烂香蕉"},
                {"name":"西兰花"},
                {"name":"小米"},
                {"name":"螃蟹肉"},
                {"name":"盐"},
                {"name":"鸡"},
                {"name":"鸭"},
                {"name":"鸡鸭骨"},
                {"name":"鸭腿骨"},
                {"name":"油条"},
                {"name":"废弃油脂"},
                {"name":"柚子"},
                {"name":"晾干的柚子皮"},
                {"name":"晒干的柚子皮"},
                {"name":"杂草"},
                {"name":"芝麻"},
                {"name":"过期芝士"},
                {"name":"猪蹄"},
                {"name":"废中药材"},
                {"name":"中草药"},
                {"name":"白菜叶"},
                {"name":"圣女果"},
                {"name":"巴旦木壳果"},
                {"name":"水果果肉"},
                {"name":"干拌面"},
                {"name":"冰糖"},
                {"name":"调料包"},
                {"name":"蛏子"},
                {"name":"宠物粮食"},
                {"name":"过期的粮食"},
                {"name":"豆腐乳"},
                {"name":"香肠"},
                {"name":"冷冻食品"},
                {"name":"蛤蜊肉"},
                {"name":"黄泥螺"},
                {"name":"火腿"},
                {"name":"花草"},
                {"name":"牡蛎肉"},
                {"name":"皮皮虾"},
                {"name":"青草 "},
                {"name":"黑豆"},
                {"name":"厨余垃圾"},
                {"name":"生蚝"},
                {"name":"干树枝"},
                {"name":"猪"}
            ],
            options_gan: [
                {"name":"塑料袋"},
                {"name":"面膜"},
                {"name":"奶茶杯"},
                {"name":"纸巾"},
                {"name":"湿纸巾"},
                {"name":"湿的纸巾"},
                {"name":"餐巾纸"},
                {"name":"使用过的餐巾纸"},
                {"name":"卫生巾"},
                {"name":"用过的卫生巾"},
                {"name":"头发"},
                {"name":"湿头发"},
                {"name":"骨头"},
                {"name":"吸管"},
                {"name":"塑料吸管"},
                {"name":"使用过的吸管"},
                {"name":"珍珠奶茶盒"},
                {"name":"口香糖"},
                {"name":"吃过的口香糖"},
                {"name":"碱性无汞电池"},
                {"name":"奶茶杯子"},
                {"name":"猪骨头"},
                {"name":"粽叶"},
                {"name":"粽子线"},
                {"name":"狗屎纸"},
                {"name":"化妆品"},
                {"name":"过期化妆品"},
                {"name":"化妆棉"},
                {"name":"尿不湿"},
                {"name":"避孕套"},
                {"name":"玉米叶"},
                {"name":"猫砂"},
                {"name":"核桃壳"},
                {"name":"茶包"},
                {"name":"卫生纸"},
                {"name":"湿巾"},
                {"name":"洗面奶"},
                {"name":"垃圾袋"},
                {"name":"玉米衣"},
                {"name":"塑料奶茶杯"},
                {"name":"包装袋"},
                {"name":"指甲"},
                {"name":"臭袜子"},
                {"name":"打火机"},
                {"name":"干燥剂"},
                {"name":"零食包装袋"},
                {"name":"厕纸"},
                {"name":"使用过的纸质餐盒"},
                {"name":"贝壳"},
                {"name":"外卖盒"},
                {"name":"口红"},
                {"name":"海绵"},
                {"name":"烟盒"},
                {"name":"香烟"},
                {"name":"烟头"},
                {"name":"香烟灰"},
                {"name":"香烟过滤嘴"},
                {"name":"胶水"},
                {"name":"502胶水"},
                {"name":"504胶水"},
                {"name":"胶带"},
                {"name":"固体胶"},
                {"name":"胶棒"},
                {"name":"玻璃胶"},
                {"name":"酸奶盖"},
                {"name":"豆浆袋"},
                {"name":"鼻屎"},
                {"name":"冰袋"},
                {"name":"笔芯"},
                {"name":"打包盒"},
                {"name":"镜子"},
                {"name":"快速包装盒"},
                {"name":"榴莲壳"},
                {"name":"面膜包装"},
                {"name":"眼镜(盒)"},
                {"name":"隐形眼镜"},
                {"name":"擦眼镜布"},
                {"name":"核桃壳"},
                {"name":"牙刷"},
                {"name":"胶囊咖啡"},
                {"name":"咖啡滤纸"},
                {"name":"咖啡纸杯盖"},
                {"name":"泡面盒"},
                {"name":"剃须刀"},
                {"name":"一次性杯子"},
                {"name":"一次性勺子"},
                {"name":"一次性拖鞋"},
                {"name":"一次性筷子"},
                {"name":"纸杯"},
                {"name":"酸奶袋"},
                {"name":"猪大骨"},
                {"name":"卫生巾包装袋"},
                {"name":"花蛤"},
                {"name":"花蛤壳"},
                {"name":"瓷器杯子"},
                {"name":"衣服吊牌"},
                {"name":"订书钉"},
                {"name":"纸尿裤"},
                {"name":"使用过的纸尿裤"},
                {"name":"海绵垫"},
                {"name":"酒精棉"},
                {"name":"少量泥土"},
                {"name":"厕纸"},
                {"name":"湿卫生巾"},
                {"name":"棉质卫生巾"},
                {"name":"椰子"},
                {"name":"木头铅笔"},
                {"name":"药膏"},
                {"name":"飞机杯"},
                {"name":"快递袋"},
                {"name":"泡沫纸"},
                {"name":"茶叶包"},
                {"name":"棒棒糖杆"},
                {"name":"胡桃壳"},
                {"name":"擦屎纸"},
                {"name":"保鲜袋"},
                {"name":"保鲜膜"},
                {"name":"无纺布袋"},
                {"name":"创口贴"},
                {"name":"大棒骨"},
                {"name":"成人尿布"},
                {"name":"除湿剂"},
                {"name":"蛋糕盒"},
                {"name":"发胶"},
                {"name":"肥皂"},
                {"name":"猫毛"},
                {"name":"狗毛"},
                {"name":"化妆品包装袋"},
                {"name":"塑料购物袋"},
                {"name":"打扫的灰尘"},
                {"name":"回形针"},
                {"name":"快递冰袋"},
                {"name":"蜡烛"},
                {"name":"灰尘毛发"},
                {"name":"粘鼠板"},
                {"name":"铅笔芯"},
                {"name":"烧烤棒"},
                {"name":"锡纸"},
                {"name":"口香糖包装袋"},
                {"name":"卫生间废纸"},
                {"name":"狗尿布"},
                {"name":"牙膏软管"},
                {"name":"废弃的圆珠笔"},
                {"name":"椰子壳"},
                {"name":"有粪便的尿布"},
                {"name":"塑料膜"},
                {"name":"雨伞"},
                {"name":"注射器"},
                {"name":"卫生棉"},
                {"name":"跳蛋"},
                {"name":"毛巾"},
                {"name":"牛奶袋"},
                {"name":"蚊香"},
                {"name":"香精"},
                {"name":"猫砂"},
                {"name":"电蚊香"},
                {"name":"花甲壳"},
                {"name":"旧衣服"},
                {"name":"耳屎"},
                {"name":"榴莲果壳"},
                {"name":"扇贝壳"},
                {"name":"雪糕棒"},
                {"name":"编织袋"},
                {"name":"乳胶手套"},
                {"name":"碗"},
                {"name":"化妆刷"},
                {"name":"绷带"},
                {"name":"潮湿塑料袋"},
                {"name":"防腐剂"},
                {"name":"发票"},
                {"name":"防晒霜瓶罐"},
                {"name":"狗屎垫"},
                {"name":"坚果"},
                {"name":"坚果壳"},
                {"name":"脚皮"},
                {"name":"冷饮包装"},
                {"name":"报纸"},
                {"name":"冰淇淋木棒"},
                {"name":"棉签"},
                {"name":"内裤"},
                {"name":"气泡袋"},
                {"name":"食品塑封布"},
                {"name":"水粉颜料"},
                {"name":"手机壳"},
                {"name":"丝袜"},
                {"name":"陶瓷"},
                {"name":"食品用脱氧剂"},
                {"name":"橡皮筋"},
                {"name":"牙签"},
                {"name":"牙线"},
                {"name":"羊蝎子骨头"},
                {"name":"验孕棒"},
                {"name":"蒸汽眼罩"},
                {"name":"大骨(如:猪腿骨)"},
                {"name":"蛇皮袋"},
                {"name":"绳子"},
                {"name":"洗发水"},
                {"name":"头皮屑"},
                {"name":"碳纤维"},
                {"name":"图章"},
                {"name":"护手霜"},
                {"name":"方便面调料包"},
                {"name":"蛋挞壳"},
                {"name":"火锅包装"},
                {"name":"针"},
                {"name":"创可贴"},
                {"name":"中药包装"},
                {"name":"搅拌勺"},
                {"name":"蛏子壳"},
                {"name":"试纸"},
                {"name":"便利贴"},
                {"name":"PE塑料袋"},
                {"name":"标签"},
                {"name":"磁带"},
                {"name":"茶壶"},
                {"name":"打火机油"},
                {"name":"纸杯盖"},
                {"name":"自发热型发热贴"},
                {"name":"封箱袋"},
                {"name":"硅胶"},
                {"name":"光盘"},
                {"name":"钢丝球"},
                {"name":"花泥"},
                {"name":"火柴"},
                {"name":"徽章"},
                {"name":"内衣"},
                {"name":"包书膜"},
                {"name":"贴纸"},
                {"name":"化妆品"},
                {"name":"塑料马夹袋"},
                {"name":"牡蛎壳"},
                {"name":"木屑"},
                {"name":"面纸"},
                {"name":"带肉牛骨头"},
                {"name":"肋骨"},
                {"name":"尼龙制品"},
                {"name":"气球"},
                {"name":"润唇膏"},
                {"name":"生蚝壳"},
                {"name":"竹签"},
                {"name":"拖把"},
                {"name":"退热贴"},
                {"name":"橡胶"},
                {"name":"洗脸巾"},
                {"name":"橡皮泥"},
                {"name":"卸妆油"},
                {"name":"羊骨头"},
                {"name":"荧光笔"},
                {"name":"印泥"},
                {"name":"美术黏土"},
                {"name":"钢化膜"},
                {"name":"滤网"},
                {"name":"生石灰"},
                {"name":"针管"},
                {"name":"针头"},
                {"name":"针筒"},
                {"name":"胡子"},
                {"name":"竹子"},
                {"name":"魔方"},
                {"name":"图画"},
                {"name":"墨囊"},
                {"name":"抹布"},
                {"name":"竹席"},
                {"name":"煤渣"},
                {"name":"象牙"},
                {"name":"墨粉"},
                {"name":"毛巾"},
                {"name":"陶瓷花盆"},
                {"name":"百洁布"},
                {"name":"电热蚊香片"},
                {"name":"苍蝇拍"},
                {"name":"甘蔗皮"},
                {"name":"洗衣粉"},
                {"name":"拉拉裤"},
                {"name":"牛油果核"},
                {"name":"乒乓板"},
                {"name":"乒乓球"},
                {"name":"曲别针"},
                {"name":"小黑板"},
                {"name":"板擦"},
                {"name":"玉"},
                {"name":"保龄球"},
                {"name":"鞭炮"},
                {"name":"尺"},
                {"name":"蜡笔"},
                {"name":"卡"},
                {"name":"碟片"},
                {"name":"大头钉"},
                {"name":"粉笔"},
                {"name":"肥料"},
                {"name":"防潮剂"},
                {"name":"复写纸"},
                {"name":"画笔"},
                {"name":"木塞"},
                {"name":"假发"},
                {"name":"记号笔"},
                {"name":"鸡毛"},
                {"name":"鸡毛掸"},
                {"name":"口罩"},
                {"name":"拉链"},
                {"name":"按摩棒"},
                {"name":"炉渣"},
                {"name":"毛笔"},
                {"name":"麻绳"},
                {"name":"棉绳"},
                {"name":"美瞳"},
                {"name":"梳子"},
                {"name":"暖宝宝贴"},
                {"name":"锅盖"},
                {"name":"纽扣"},
                {"name":"墙刷"},
                {"name":"墙皮"},
                {"name":"黑胶唱片"},
                {"name":"氢气球"},
                {"name":"废弃环氧树脂"},
                {"name":"润发乳"},
                {"name":"沐浴露"},
                {"name":"乳胶枕"},
                {"name":"扫把"},
                {"name":"鼠标垫"},
                {"name":"砂锅"},
                {"name":"石膏"},
                {"name":"手帕"},
                {"name":"文胸"},
                {"name":"宣纸"},
                {"name":"修正带"},
                {"name":"浴帽"},
                {"name":"油画棒(笔)"},
                {"name":"羽毛球(拍)"},
                {"name":"雨披"},
                {"name":"羊蝎子"},
                {"name":"雨衣"},
                {"name":"油纸"},
                {"name":"吸油纸"},
                {"name":"保温材料"}
            ]
        }
    },
    methods:{
        handleReturnHome(){
            this.$router.go(-1);
        },
        handleChecked(obj){
            // console.log(obj);
            this.active = obj;
        },
        handleSearch(){
            this.show = false;
            // console.log('搜索结果',garbage.filter(item => (item.name).indexOf(this.value) > -1));
        },
        handleShow(){
            this.show = false;
        },
        handleKeyWord(){
            this.list = garbage.filter(item => (item.name).indexOf(this.value) > -1);
        },
        handleCancel(){
            this.show = true;
        } 
    },
    created(){
        
    }
}
</script>
<style lang="less" scoped>
    #page-garbage{
        width: 100vw;
        height: calc(100vh - 86px);
        padding-top: 86px;
        .search{
            width: 90vw;
            height: 80px;
            margin: 20px auto;
            background: #f2f2f2;
            box-sizing: border-box;
            padding-left: 20px;
            border-radius: 50px;
            font-size: 28px;
        }
        .type{
            width: 100vw;
            height: 80px;
            background: #f2f2f2;
            .per-type{
                width: 25%;
                height: 100%;
                font-size: 28px;
            }
            .active{
                background: #D18C4C;
                color: #fff;
            }
        }
        .answer{
            width: 100vw;
            height: calc(100vh - 86px);
            position: fixed;
            top: 86px;
            left: 0px;
            z-index: 5;
            background: #f2f2f2;
            .top{
                width: 100%;
                height: 80px;
                box-sizing: border-box;
                padding-left: 20px;
                background: #f2f2f2;
                border-bottom: solid 1px #ccc;
                >div:nth-child(1){
                    width: 80%;
                    height: 100%;
                    .input{
                        width: 100%;
                        height: 90%;
                        border: none;
                        background: transparent;
                        font-size: 26px; 
                    }
                    input::-webkit-input-placeholder{
                        padding-top: 10px;
                        font-size: 28px;
                    }
                }
                >div:nth-child(2){
                    width: 20%;
                    height: 100%;
                    font-size: 28px;
                }
            }
            .list{
                width: 80%;
                height: calc(100vh - 300px);
                margin: auto;
                overflow-y: scroll;
                background: #fff;
                border-radius: 20px;
                box-sizing: border-box;
                margin-top: 20px;
                >div{
                    width: 100%;
                    height: 60px;
                    padding: 10px 20px;
                    margin: auto;
                    box-sizing: border-box;
                }
            }
        }
        .detail{
            width: 100%;
            height: 800px;
            font-size: 28px;
            line-height: 50px;
            .top{
                width: 90%;
                height: auto;
                background: #EFEDEB;
                margin: 10px auto;
                box-sizing: border-box;
                padding: 20px;
                text-align: justify;
                border-radius: 15px;
                .title-desc{
                    width: 80%;
                    height: auto;
                    margin: auto;
                }
            }
            .list{
                width: 90%;
                height: auto;
                background: #f2f2f2;
                margin: 10px auto;
                box-sizing: border-box;
                padding: 20px;
                text-align: justify;
                border-radius: 15px;
            }
        }
    }
</style>
